spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo
    username: vusala01
    password: Butterfly2001
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

  liquibase:
    enabled: false

server:
  port: 8099
